### PR TITLE
Main

### PR DESCRIPTION
**Pull request by hedjour**
Use of or Statement inplace of elif.
Macos Sonoma is out Is it change the macos $OSTYPE variable ?

### CODE REVIEW

**Comment by NicoKiaru** [comment]
> Macos Sonoma is out Is it change the macos $OSTYPE variable ?

I hope not !

Thanks again, for the PR!

**Comment by hedjour** [comment]
Need to be test ;)
I work on the proxy bug... and try to understand how works the Groovy script to rewrite them in bash.

**Comment by NicoKiaru** [comment]
Humm, I think that's a real pain, and since I wouldn't be able to understand it, I would discourage you to do it... However, if you want to do it, I'd go for either: 
- run a pure java app with the shipped jdk of QuPath
- or run this groovy script by launching qupath in cli mode

**Comment by NicoKiaru** [comment]
Why I'm saying is that there's a bit of 'update logic' with the names of the jars that's going to be a mess to do in bash + there's a specificity regarding OMERO.

**Pull request merged**
